pool:
  vmImage: Ubuntu 16.04
steps:
  - task: InstallMATLAB@0
  - task: RunMATLABTests@0
    inputs:
      sourceFolder: source
      codeCoverageCobertura: coverage.xml
  - script: bash <(curl -s https://codecov.io/bash)
